In [2]:
import pandas as pd

In [4]:
stats = pd.read_csv("player_mvp_stats.csv")

In [6]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,...,0.0,0.000,Phoenix Suns,59,23,0.720,0.0,110.6,106.8,3.86
1,1,Aaron Swinson,SF,24,PHO,9,0,5.7,1.1,2.0,...,0.0,0.000,Phoenix Suns,59,23,0.720,0.0,110.6,106.8,3.86
2,2,Antonio Lang,SF,22,PHO,12,0,4.4,0.3,0.8,...,0.0,0.000,Phoenix Suns,59,23,0.720,0.0,110.6,106.8,3.86
3,3,Charles Barkley,PF,31,PHO,68,66,35.0,8.1,16.8,...,1050.0,0.091,Phoenix Suns,59,23,0.720,0.0,110.6,106.8,3.86
4,4,Dan Majerle,SF,29,PHO,82,46,37.7,5.3,12.6,...,0.0,0.000,Phoenix Suns,59,23,0.720,0.0,110.6,106.8,3.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13667,13667,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
13668,13668,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
13669,13669,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
13670,13670,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
13671,13671,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.000,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [8]:
del stats["Unnamed: 0"]

In [12]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          54
3P            0
3PA           0
3P%        1854
2P            0
2PA           0
2P%          98
eFG%         54
FT            0
FTA           0
FT%         514
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [20]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]]

                Player  FTA
22          John Coker  0.0
37        Jason Sasser  0.0
48     Adrian Caldwell  0.0
64        Bruno Šundov  0.0
103     Jamal Robinson  0.0
...                ...  ...
13492      George King  0.0
13578     Trevor Keels  0.0
13586      Luke Zeller  0.0
13634      Malcolm Lee  0.0
13668      Steve Novak  0.0

[514 rows x 2 columns]

In [22]:
stats = stats.fillna(0)

In [26]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [28]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS']

In [32]:
train = stats[stats["Year"] < 2023]

In [34]:
test = stats[stats["Year"] == 2023] #splitting the data into training and test sets

In [38]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /opt/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in /opt/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /opt/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from scikit-learn) (2.2.0)

In [40]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [42]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [46]:
predictions = reg.predict(test[predictors])

In [48]:
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [50]:
predictions

       predictions
125       0.003323
126       0.030629
127       0.036790
128       0.223148
129      -0.000350
...            ...
13574    -0.013689
13575     0.004279
13576    -0.012570
13577     0.021243
13578     0.011371

[539 rows x 1 columns]

In [54]:
combo = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [56]:
combo

                      Player  Share  predictions
125               A.J. Green  0.000     0.003323
126             Bobby Portis  0.000     0.030629
127              Brook Lopez  0.000     0.036790
128    Giannis Antetokounmpo  0.606     0.223148
129             Goran Dragić  0.000    -0.000350
...                      ...    ...          ...
13574      Mitchell Robinson  0.000    -0.013689
13575             Obi Toppin  0.000     0.004279
13576         Quentin Grimes  0.000    -0.012570
13577             RJ Barrett  0.000     0.021243
13578           Trevor Keels  0.000     0.011371

[539 rows x 3 columns]

In [84]:
combo.sort_values("Share", ascending=False).head(10)

                        Player  Share  predictions   Rk
13369              Joel Embiid  0.915     0.195818  516
636               Nikola Jokić  0.674     0.170110   68
128      Giannis Antetokounmpo  0.606     0.223148    4
2695              Jayson Tatum  0.280     0.135242  131
1222   Shai Gilgeous-Alexander  0.046     0.145228  106
12338         Donovan Mitchell  0.030     0.083924  458
3943          Domantas Sabonis  0.027     0.093792  185
220                Luka Dončić  0.010     0.193217   32
6202             Stephen Curry  0.005     0.105812  288
9860              Jimmy Butler  0.003     0.108942  375

In [66]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combo["Share"], combo["predictions"])

0.0026529069114962756

In [72]:
combo["Share"].value_counts() #too many players have no share of mvp votes for this to work

Share
0.000    526
0.001      2
0.606      1
0.674      1
0.010      1
0.046      1
0.280      1
0.027      1
0.002      1
0.005      1
0.003      1
0.030      1
0.915      1
Name: count, dtype: int64

In [90]:
combo = combo.sort_values("Share", ascending=False)
combo["Rk"] = list(range(1,combo.shape[0]+1))

In [92]:
combo.head(10)

                        Player  Share  predictions  Rk
13369              Joel Embiid  0.915     0.195818   1
636               Nikola Jokić  0.674     0.170110   2
128      Giannis Antetokounmpo  0.606     0.223148   3
2695              Jayson Tatum  0.280     0.135242   4
1222   Shai Gilgeous-Alexander  0.046     0.145228   5
12338         Donovan Mitchell  0.030     0.083924   6
3943          Domantas Sabonis  0.027     0.093792   7
220                Luka Dončić  0.010     0.193217   8
6202             Stephen Curry  0.005     0.105812   9
9860              Jimmy Butler  0.003     0.108942  10

In [96]:
combo = combo.sort_values("predictions", ascending=False)
combo["Predicted_Rk"] = list(range(1,combo.shape[0]+1))

In [98]:
combo.head(10)

                        Player  Share  predictions   Rk  Predicted_Rk
128      Giannis Antetokounmpo  0.606     0.223148    3             1
13369              Joel Embiid  0.915     0.195818    1             2
220                Luka Dončić  0.010     0.193217    8             3
636               Nikola Jokić  0.674     0.170110    2             4
1222   Shai Gilgeous-Alexander  0.046     0.145228    5             5
7464            Damian Lillard  0.000     0.137896  293             6
10432             Kevin Durant  0.000     0.137006  396             7
2695              Jayson Tatum  0.280     0.135242    4             8
7796             Anthony Davis  0.000     0.133679  312             9
7803              LeBron James  0.000     0.129874  319            10

In [102]:
combo.sort_values("Share", ascending=False).head(10)

                        Player  Share  predictions  Rk  Predicted_Rk
13369              Joel Embiid  0.915     0.195818   1             2
636               Nikola Jokić  0.674     0.170110   2             4
128      Giannis Antetokounmpo  0.606     0.223148   3             1
2695              Jayson Tatum  0.280     0.135242   4             8
1222   Shai Gilgeous-Alexander  0.046     0.145228   5             5
12338         Donovan Mitchell  0.030     0.083924   6            24
3943          Domantas Sabonis  0.027     0.093792   7            17
220                Luka Dončić  0.010     0.193217   8             3
6202             Stephen Curry  0.005     0.105812   9            14
9860              Jimmy Butler  0.003     0.108942  10            13

In [112]:
def find_ap(combo): #for finding error metric
    actual = combo.sort_values("Share", ascending=False).head(5) #sort the data by highest mvp vote share and take the top 5 players
    predicted = combo.sort_values("predictions", ascending=False) #look at predictions and sort them
    ps = []
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row["Player"] in actual["Player"].values: #if the player in the predicted top 5 is in the actual top 5
            found += 1
            ps.append(found/seen)
        seen += 1
    return sum(ps) / len(ps)

In [110]:
find_ap(combo)

0.835

In [114]:
years = list(range(1995,2023))

In [126]:
aps= []
all_predictions = []
for year in years[5:]: # looking from years 20001 and on, run the same code to find the error metric as before
    train = stats[stats["Year"] <year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors], train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combo = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combo)
    aps.append(find_ap(combo))

In [124]:
sum(aps) / len(aps)

0.7363349607222165

In [128]:
def add_ranks(combo): #add in diagnostics for the machine learning algorithm
    combo = combo.sort_values("Share", ascending=False)
    combo["Rk"] = list(range(1,combo.shape[0]+1))
    combo = combo.sort_values("predictions", ascending=False)
    combo["Predicted_Rk"] = list(range(1,combo.shape[0]+1))
    combo["Diff"] = combo["Rk"] - combo["Predicted_Rk"]
    return combo

In [140]:
ranking = add_ranks(all_predictions[1])
ranking[ranking["Rk"] < 6].sort_values("Diff", ascending=False)

                 Player  Share  predictions  Rk  Predicted_Rk  Diff
11969  Shaquille O'Neal  0.466     0.272036   3             1     2
9348       Chris Webber  0.420     0.157423   4             2     2
8817         Tim Duncan  0.569     0.137012   2             3    -1
8404      Kevin Garnett  0.122     0.115111   5             7    -2
1003      Allen Iverson  0.904     0.123538   1             5    -4

In [148]:
def backtest(stats, model, year, predictors): #single function for backtesting
    aps= []
    all_predictions = []
    for year in years[5:]: # looking from years 20001 and on, run the same code to find the error metric as before
        train = stats[stats["Year"] <year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors], train["Share"])
        predictions = reg.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combo = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combo = add_ranks(combo)
        all_predictions.append(combo)
        aps.append(find_ap(combo))
    return sum(aps)/len(aps), aps, pd.concat(all_predictions) #mean average percision (sum(aps)/len(aps))

In [144]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [146]:
mean_ap

0.7363349607222165

In [152]:
all_predictions[all_predictions["Rk"] <= 5].sort_values("Diff").head(10) #check all predictions to see the biggest differences from top 5 mvp candidates

                 Player  Share  predictions  Rk  Predicted_Rk  Diff
1324         Jason Kidd  0.712     0.015312   2           100   -98
5190         Steve Nash  0.839     0.041184   1            41   -40
12428       Joakim Noah  0.258     0.044454   4            40   -36
8453    Peja Stojaković  0.228     0.034305   4            39   -35
5208         Steve Nash  0.739     0.060247   1            31   -30
3694   Chauncey Billups  0.344     0.056507   5            33   -28
1489         Chris Paul  0.138     0.071483   5            33   -28
880        Devin Booker  0.216     0.088936   4            17   -13
5223         Steve Nash  0.785     0.085181   2            14   -12
6815        Kobe Bryant  0.291     0.076329   4            15   -11

In [162]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0,ascending=False) #checking to see what the model thinks are the most important predictors

           0     1
13  0.083802  eFG%
18  0.033488   DRB
17  0.021747   ORB
29  0.019212  W/L%
10  0.016285    2P
15  0.011598   FTA
21  0.009690   STL
22  0.008639   BLK
25  0.007895   PTS
20  0.007162   AST
12  0.007072   2P%
5   0.006446   FGA
7   0.002541    3P
4   0.000421    FG
30  0.000298    GB
0   0.000240   Age
27  0.000142     W
1   0.000092     G
2   0.000010    GS
26 -0.000218  Year
31 -0.000301  PS/G
28 -0.000336     L
32 -0.000357  PA/G
33 -0.000552   SRS
24 -0.003456    PF
3  -0.003728    MP
16 -0.004013   FT%
23 -0.007978   TOV
14 -0.008400    FT
9  -0.012027   3P%
8  -0.012029   3PA
11 -0.018123   2PA
19 -0.026842   TRB
6  -0.148886   FG%

In [178]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year", as_index=False).apply(lambda x: x / x.mean())
 #gets the ratio between a players stats and the average stats for that season

In [180]:
stat_ratios

               PTS       AST       STL       BLK        3P  Year
0  0      1.319103  0.758048  0.991605  0.931570  1.107162   1.0
   1      0.317998  0.151610  0.141658  0.000000  0.000000   1.0
   2      0.105999  0.050537  0.000000  0.465785  0.000000   1.0
   3      2.708873  2.071999  2.266527  1.630247  2.435757   1.0
   4      1.837322  2.071999  1.699895  1.164462  5.314379   1.0
...            ...       ...       ...       ...       ...   ...
28 13574  0.811285  0.435028  1.476263  4.707424  0.000000   1.0
   13575  0.811285  0.483365  0.492088  0.523047  1.312418   1.0
   13576  1.238854  1.015066  1.148205  1.046094  2.221015   1.0
   13577  2.148808  1.353421  0.656117  0.523047  1.716239   1.0
   13578  0.109633  0.000000  0.000000  0.000000  0.302866   1.0

[13672 rows x 6 columns]

In [220]:
# Resetting indices to ensure they match
stat_ratios.reset_index(drop=True, inplace=True)
stats.reset_index(drop=True, inplace=True)

# Now attempt the assignment
# Correcting column names for assignment
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]
stats.drop(columns=['PTS_R'], inplace=True)

In [224]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W/L%,GB,PS/G,PA/G,SRS,AST_R,STL_R,BLK_R,3P_R,PTS_T
0,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,0.504,...,0.72,0.0,110.6,106.8,3.86,0.758048,0.991605,0.931570,1.107162,1.319103
1,Aaron Swinson,SF,24,PHO,9,0,5.7,1.1,2.0,0.556,...,0.72,0.0,110.6,106.8,3.86,0.151610,0.141658,0.000000,0.000000,0.317998
2,Antonio Lang,SF,22,PHO,12,0,4.4,0.3,0.8,0.400,...,0.72,0.0,110.6,106.8,3.86,0.050537,0.000000,0.465785,0.000000,0.105999
3,Charles Barkley,PF,31,PHO,68,66,35.0,8.1,16.8,0.486,...,0.72,0.0,110.6,106.8,3.86,2.071999,2.266527,1.630247,2.435757,2.708873
4,Dan Majerle,SF,29,PHO,82,46,37.7,5.3,12.6,0.425,...,0.72,0.0,110.6,106.8,3.86,2.071999,1.699895,1.164462,5.314379,1.837322

In [226]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [228]:
mean_ap

0.7363349607222165

In [234]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes

In [238]:
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [240]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[28:], predictors)

In [241]:
mean_ap

0.7755680106295854

In [242]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[28:], predictors)

In [243]:
mean_ap

0.7363349607222165

In [267]:
all_predictions[all_predictions["Rk"] <= 5]

                      Player  Share  predictions  Rk  Predicted_Rk  Diff
88          Shaquille O'Neal  0.998     0.224869   1             1     0
1694             Karl Malone  0.258     0.160038   4             2     2
4799         Alonzo Mourning  0.303     0.122102   3             4    -1
8802              Tim Duncan  0.205     0.107350   5             7    -2
5673           Kevin Garnett  0.337     0.097901   2            11    -9
...                      ...    ...          ...  ..           ...   ...
10855  Giannis Antetokounmpo  0.595     0.214087   3             1     2
810              Joel Embiid  0.706     0.184606   2             2     0
620             Nikola Jokić  0.875     0.183725   1             3    -2
10689            Luka Dončić  0.146     0.155094   5             4     1
880             Devin Booker  0.216     0.088936   4            17   -13

[115 rows x 6 columns]